import type { Metadata } from "next";

import { Inter } from "next/font/google";

import "./globals.css";

import Navbar from "./components/navbar/Navbar";

import LoginModal from "./components/modals/LoginModal";

import SignupModal from "./components/modals/SignupModal";

import AddPropertyModal from "./components/modals/AddPetModal";

import SearchModal from "./components/modals/SearchModal";

import Footer from "./components/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pet Adoption",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const content = (
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ab, pariatur nam dignissimos nisi inventore. Cumque id aspernatur facilis nam temporibus delectus quam, iure omnis aliquam dolorem dolore voluptatem exercitationem?</p>
  )


  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />        
        <div className="pt-44">          
          {children}
          <Footer/>
        </div>    
      <LoginModal />
      <SearchModal />
      <SignupModal />
      <AddPropertyModal />
      </body>    
    </html>
  );
}