# Generated by Django 4.2.11 on 2024-04-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_pet_adoption_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adoption_status',
            field=models.CharField(max_length=25),
        ),
    ]
