# Generated by Django 4.2.11 on 2024-04-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_pet_adoption_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='behaviour',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='other_medical_history',
            field=models.TextField(blank=True),
        ),
    ]
