# Generated by Django 4.2.11 on 2024-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_pet_image_delete_petimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='/media/tux-linux.jpg', upload_to='uploads/pets'),
        ),
    ]
