# Generated by Django 4.2.11 on 2024-04-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_adoptionrequest_delete_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adoption_status',
            field=models.BooleanField(default=True),
        ),
    ]
