# Generated by Django 4.2.11 on 2024-04-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_rename_landlord_pet_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionrequest',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='adoptionrequest',
            old_name='status',
            new_name='adoption_status',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='availability_for_meet_and_greets',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='pet_care_experience',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='has_pet',
            field=models.BooleanField(default=False),
        ),
    ]
