# Generated by Django 4.2.11 on 2024-04-25 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_reportpet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/pet_images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pet.pet')),
            ],
        ),
    ]
