# Generated by Django 4.2.11 on 2024-04-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_remove_pet_image_petimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='tux-linux.jpg', upload_to='uploads/pets'),
        ),
        migrations.DeleteModel(
            name='PetImage',
        ),
    ]
